name: "build-test"
on: [push]

jobs:
  test_something:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Use the latest version of checkout
      - name: Create a test output
        id: test
        run: echo "summary=Test successful" >> $GITHUB_ENV  # Use environment files instead
      - uses: LouisBrunner/checks-action@v2.0.0
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test XYZ
          conclusion: ${{ job.status }}
          output: |
            {"summary":"${{ env.summary }}"}
