name: Dependency Audit

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at midnight
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install safety pip-audit

      - name: Run Safety (Security Check)
        run: safety check --full-report

      - name: Run pip-audit (Dependency Vulnerability Scan)
        run: pip-audit