name: Push to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  push_to_hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install HF CLI
        run: pip install huggingface_hub

      - name: Login to Hugging Face
        run: huggingface-cli login --token ${{ secrets.HF_TOKEN }}

      - name: Push Model / Dataset / Space
        run: |
          hf_repo="your_hf_username/your_repo_name"
          huggingface-cli repo create $hf_repo --type model --exist-ok
          git lfs install
          git add .
          git commit -m "Auto update"
          git push https://huggingface.co/$hf_repo main